version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      # Angenommen, 'requirements.txt' ist relativ zu Ihrem Quellverzeichnis, z.B. 'terraform/requirements.txt'
      - pip install -r terraform/requirements.txt
  pre_build:
    commands:
      - echo Pre-build steps...
  build:
    commands:
      - echo Running unit tests...
      - pytest
  post_build:
    commands:
      - echo Build and test completed on `date`

artifacts:
  files:
    - app.py
    - terraform/requirements.txt # Pfad aktualisieren, wenn die Datei als Artefakt gespeichert werden soll
    - templates/**
  discard-paths: yes
